#ifndef CONFIGURATION_H
#define CONFIGURATION_H


// SELECT MCU

// #define MCU_IS_ESP32_WROOM_DA_MODULE
#define MCU_IS_ESP32_S2_MINI
// #define MCU_IS_RASPBERRY_PI_PICO_W


// FIRMWARE VERSION
const std::string kFirmwareVersion = "1.0";


// SELECT DISPLAY

#define DISPLAY_IS_ST7789V
// #define DISPLAY_IS_ST7735
// #define DISPLAY_IS_ILI9341
// #define DISPLAY_IS_ILI9488


// SELECT IF TOUCHSCREEN IS PRESENT

// #define TOUCHSCREEN_IS_XPT2046


// SELECT IF WIFI IS USED

#define WIFI_IS_USED


#endif  // CONFIGURATION_H